CREATE TABLE users (
  user_id TEXT PRIMARY KEY,
  name TEXT,
  nickname TEXT,
  email TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
